### ISSUE TITLE
Token auth doesn't work

### ISSUE THREAD

**Issue by SteshinSS** [negezor/vk-cleaner#1]
I selected token authorization and opened the [suggested link](https://oauth.vk.com/authorize?client_id=3116505&scope=1073737727&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token&revoke=1
). Here is the response:
`{"error":"invalid_request","error_description":"application is disabled"}`

**Comment by negezor** [comment]
Fixed https://github.com/negezor/vk-cleaner/commit/65da5c31fda9951cf904c45bfa2d14595bf7c2b2
